config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :locations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  def postcode
    address.partition('|').last
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:update, :show, :edit]
  
  def index
    @locations = Location.all
    @locations.each do |location|
      @marker = 
      {
        lat: location.latitude,
        lng: location.longitude,
      }
    end
  end

  def show
    @marker = 
      {
        lat: @location.latitude,
        lng: @location.longitude,
      }
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(strong_params)
    if @location.save
      redirect_to location_path(@location.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @location.update(strong_params)
    redirect_to location_path(@location.id)
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    
  end

  private
  def set_location
    @location = Location.find(params[:id])
  end

  def strong_params
    params.require(:location).permit(:name,:address, :postcode)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatchmentArea</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    
    <!--  Include google maps api -->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&key=<%= ENV['GOOGLE_API'] %>"type="text/javascript"></script>
    <!--  Include targomo googlemaps full build -->
    <script src="https://releases.targomo.com/googlemaps/latest-full.min.js" type="text/javascript"></script>
    
    <%# <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.js"></script>
    <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.css" rel="stylesheet"> %>
    <!--  Include targomo core -->
    <%# <script src="https://releases.targomo.com/core/latest.min.js"></script> %>
    <!-- Include chartjs for adding charts -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <!--  Include micro progress bar  -->
    <script src="https://www.targomo.com/developers/scripts/mipb.min.js"></script>
    <!--  Leaflet  -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" >
    <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js" crossorigin=""></script>
    <script src="https://releases.targomo.com/leaflet/latest.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.3.2/html2canvas.min.js" integrity="sha512-tVYBzEItJit9HXaWTPo8vveXlkK62LbA+wez9IgzjTmFNLMBO1BEYladBw2wnM3YURZSMUyhayPCoLtjGh84NQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.js"></script>
    <script src="https://cdn.maptiler.com/mapbox-gl-js/v1.5.1/mapbox-gl.js"></script>
    <script src="https://cdn.maptiler.com/mapbox-gl-leaflet/latest/leaflet-mapbox-gl.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.css" />
    <link rel="stylesheet" href="https://cdn.maptiler.com/mapbox-gl-js/v1.5.1/mapbox-gl.css" />

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<%= 'hello' %>
<table>
  <thead> 
    <tr class="header"> 
      <th > </th>
      <th>Name</th>
      <th>City</th>
      <th>Address</th>
      <th>Size</th>
      <th>Vacant Units</th>
      <th>More Info</th>
      <th>Catchment 15min</th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location| %>
        <tr class="location_row" data-targomo-api-key="<%= ENV['TARGOMO_API'] %>" data-marker="<%= {lat: location.latitude, lng: location.longitude}.to_json  %>"> 
          <td> <%= link_to "Delete", location_path(location.id), method: :delete %> </td>
          <td> <%= link_to location.name, location_path(location.id) %> </td>
          <td> <%= location.city %> </td>
          <td> <%= location.address %> </td>
          <td> <%= location.size %> </td>
          <td> <%= location.vacant_units %> </td>
          <td> <%= link_to "CR_link", location.url %> </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/locations/new.html.erb
<div class="row m-0">
  <div class="left-col col-6 p-5">
    <h4 class="text-info mt-3 pt-3">Area you want to explore</h4>
    <div class="form-top">
      <p class="text-secondary mt-5">Let's start with the basics</p>
      <h5 class="text-muted"></h5>
      <%= simple_form_for @location do |f| %>
      <%= f.input :name, label: false, placeholder: 'Area Name' %>
      <div class="row">
        <div class="col-6">
         <%= f.input :address, label: false, placeholder: 'Address' %>
        </div>
      </div>
      <%= f.button :submit, type: "submit", class: "btn btn-secondary" %>
    <% end %>
    </div>


  </div>
  <%# <div class="right-col col-6 vh-100" style="background-image: url('<%= image_path("lunch.jpg") %>

app/views/locations/show.html.erb
<%= link_to "New Location", new_location_path %>
<div>
  <button id="generateScreenshot"> Save Image </button>
</div>
<div class="slide_container">
  <h2> <%= @location.name %> - Last 15min Drive Analytics</h2>
  <div class="show_grid">
    
    <div class="demographics">
    <h4>Population Metrics</h4>
    </div>
    <div class="map_container">
      <h4> Outcodes reached within a 15min drive </h4>
      <div id="map" 
          data-marker="<%= @marker.to_json %>"
          data-targomo-api-key="<%= ENV['TARGOMO_API'] %>" >
          <div class="legend">
            <div><i id="legend-square" class="fas fa-square"></i></span>15 min Drive Catchment</div>
            <div><i id="legend-star" class="fas fa-star"></i></span> <%= @location.name %></div>
          </div>
          <div id="map_box" class="hide"></div>
      </div>
    </div>
    
    <div id="sold_values">
        <h4> Current Trends in the local Residential Market </h4>
        <table id="value_table">
          <thead> 
            <tr> 
              <th colspan="2"></th>
              <th colspan="3" id="increase">% Value Increase</th>
            </tr>
              <tr class="sub_header"> 
              <th class="outcode">Outcode</th>
              <th>Value 2021</th>
              <th>2019</th>
              <th>2020</th>
              <th>2021</th>
            </tr>
          </thead>
        </table>
        <div class="average_growth">
        
        </div>
    </div>
  </div>
</div>

<div id="map_hide" 
    data-marker="<%= @marker.to_json %>"
    data-targomo-api-key="<%= ENV['TARGOMO_API'] %>" >
</div>
<div id="chart">
    <canvas id="canvas"></canvas>
</div>
<div id="map_leaflet"></div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>